### ISSUE TITLE
Add caching of deleted and added jokes in submission script

### ISSUE THREAD

**Issue by Sv443** [Sv443/JokeAPI#356]
This is so the uniqueness score can continuously trained and its data persists.  
Currently the memory of the uniqueness calculation is lost when the process exits, which isn't ideal.  
  
#### Todo:  
- [x] Create a cache file of deleted and added jokes
- [x] Oldest entries are cleared after x amount of time passed or file size > y
- [ ] Combine cache file contents and current uniqueness memory so the fuse.js fuzzy search can source both
